name: Generate Metrics and Commit for JabRef (owner) jabref (project)

env:
  API_KEY: ${{ secrets.API_KEY }}

on:
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at 12:00 UTC
  workflow_dispatch: # Allows manual trigger from Actions tab

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1240

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Extraction Scripts
      run: |
        cd backend/functions
        python issueExtractor.py JabRef jabref $API_KEY
        python pullRequestExtractor.py JabRef jabref $API_KEY
        python milestoneExtractor.py JabRef jabref $API_KEY

    - name: List files in metrics folder
      run: |
        sudo apt-get update
        sudo apt-get install -y tree
        tree -L 3   # Adjust depth with -L

    - name: Run Processing Scripts
      run: |
        cd backend/functions
        python productivityISProcessing.py JabRef jabref
        python productivityPRProcessing.py JabRef jabref

    - name: Commit and Push Results
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "pedrorodriguesarantes@gmail.com"
        git add metrics
        git commit -m "Update metrics JSON metrics for JabRef (org) jabref (project) [skip ci]" || echo "No changes to commit"
        git push